name: XmsCore-4.1

on: [push, pull_request]


jobs:

# ----------------------------------------------------------------------------------------------
# FLAKE
# ----------------------------------------------------------------------------------------------
  flake:
    name: Tox Project (${{ matrix.platform }}-Python${{python-version}})
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, linux-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      # Checkout Sources
      - name: Checkout Source
        uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-docstrings flake8-bugbear flake8-import-order pep8-naming
      # Flake Code
      - name: Run Flake
        run: |
          tox .
